apiVersion: v2
name: freqtrade
description: A free and open source crypto trading bot written in Python
type: application
annotations:
  category: Financial
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
engine: gotpl
home: https://github.com/nightshift2k/helm-charts/tree/master/charts/freqtrade
icon: https://raw.githubusercontent.com/freqtrade/freqtrade/develop/docs/images/logo.png
keywords:
  - freqtrade
  - crypto
  - algotrading
  - python
maintainers:
  - email: join.the.nightshift@protonmail.com
    name: nightshift2k
sources:
  - https://www.freqtrade.io/
version: 0.0.3
appVersion: "2021.9"